### ISSUE TITLE
I can't find svg import or svg2d.

### ISSUE THREAD

**Issue by brendensawsomegames** [Giwayume/godot-svg#2]
I selected my svg file and went to the import tab. When I opened the 'import as' there was no option for svg.
I couldn't find any new node to add to my scene.

**Comment by Giwayume** [comment]
Is the plugin enabled?

**Comment by brendensawsomegames** [comment]
I downloaded it from the asset library.
Is there an extra step?
This is my first time using plugins.

**Comment by Giwayume** [comment]
Yes, in the menu, `Project -> Project Settings... -> Click 'Plugins' tab -> Click 'Enable' checkbox next to plugin`.

**Comment by Giwayume** [comment]
I'm gonna assume you figured this out
