### ISSUE TITLE
Unable to enable godot svg addon due to error in plugin.gd

### ISSUE THREAD

**Issue by davisnoah** [Giwayume/godot-svg#5]
So I copied the files for the plugin to my res://addons folder in my godot project but when I try to enable it, I end up getting this error: 

> Unable to load addon script from path: 'res://addons/godot_svg/plugin.gd'. This might be due to a code error in that script.
> Disabling the addon at 'res://addons/godot_svg/plugin.cfg' to prevent further errors.

The error I see for the plugin.gd file is in the attached image:

![Screen Shot 2024-10-29 at 14 31 14](https://github.com/user-attachments/assets/c6475571-142c-4421-b4e2-a863748cabe0)

**Comment by Giwayume** [comment]
It looks to me like you downloaded the code from the 3.5 branch. That is for Godot 3.5. Download the 4.3 branch instead.

https://github.com/Giwayume/godot-svg/tree/4.3

The branches are named for the Godot version they are designed for.

**Comment by davisnoah** [comment]
Thank you so much for your help. It worked like a charm. I am not so good at Github you see so I appreciate you looking out for me.
